# Logistic clamp bounds
LOGISTIC_CLAMP_MIN = -60.0
LOGISTIC_CLAMP_MAX = 60.0

# Move-quality label thresholds
MOVE_QUALITY_EXCELLENT_THRESHOLD = 0.88
MOVE_QUALITY_GOOD_THRESHOLD = 0.62
MOVE_QUALITY_OKAY_THRESHOLD = 0.38

# Fixed move-quality defaults
INITIAL_ROAD_FLEXIBLE_QUALITY = 0.3
FORCED_CHOICE_DEFAULT_QUALITY = 0.5
FORCED_CHOICE_BENEFICIAL_QUALITY = 0.7
